"""empty message

Revision ID: 2f7ab49186d1
Revises: e5529d5f33a5
Create Date: 2021-02-16 22:16:50.918762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7ab49186d1'
down_revision = 'e5529d5f33a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist_venues')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_venues',
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], name='artist_venues_artist_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], name='artist_venues_venue_id_fkey'),
    sa.PrimaryKeyConstraint('artist_id', 'venue_id', name='artist_venues_pkey')
    )
    # ### end Alembic commands ###
