"""empty message

Revision ID: 388477eb8b4b
Revises: 0ea8a99476c5
Create Date: 2021-02-14 17:30:11.659609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388477eb8b4b'
down_revision = '0ea8a99476c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.ARRAY(sa.String(length=20)), nullable=True))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.execute('UPDATE "Venue" SET seeking_talent=False WHERE seeking_talent IS NULL;')
    op.alter_column('Venue', 'seeking_talent', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
