"""empty message

Revision ID: 707a74834ef7
Revises: 388477eb8b4b
Create Date: 2021-02-15 01:38:36.938228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '707a74834ef7'
down_revision = '388477eb8b4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('UPDATE "Venue" SET genres = \'{"Other"}\' WHERE genres IS NULL;')
    op.alter_column('Venue', 'genres',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=20)),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'genres',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=20)),
               nullable=True)
    # ### end Alembic commands ###
