"""empty message

Revision ID: 7533e6a9e634
Revises: 21bd8aa602f0
Create Date: 2021-02-15 21:32:47.215248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

revision = '7533e6a9e634'
down_revision = '21bd8aa602f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genres',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=20)),
               nullable=True)
    op.execute('UPDATE "Venue" SET genres = \'{"Other"}\' WHERE genres IS NULL;')
    op.alter_column('Artist', 'genres',
                    existing_type=postgresql.ARRAY(sa.VARCHAR(length=20)),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###
