"""empty message

Revision ID: cca0a4e03361
Revises: 2f7ab49186d1
Create Date: 2021-02-16 22:58:44.834291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cca0a4e03361'
down_revision = '2f7ab49186d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'date', new_column_name='start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'start_time', new_column_name='date')
    # ### end Alembic commands ###
