"""empty message

Revision ID: e5529d5f33a5
Revises: 87c92faceac2
Create Date: 2021-02-15 23:58:12.526793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5529d5f33a5'
down_revision = '87c92faceac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.ARRAY(sa.String(length=20)), nullable=True))
    op.execute('UPDATE "Artist" SET genres=\'{"Other"}\' WHERE genres IS NULL;')
    op.alter_column('Artist', 'genres', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###
